In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('nba')
df.groupby(['Team']).mean()

                           Number        Age      Weight        Salary
Team
Atlanta Hawks           19.000000  28.200000  221.266667  4.860197e+06
Boston Celtics          31.866667  24.733333  219.466667  4.181505e+06
Brooklyn Nets           18.266667  25.600000  215.600000  3.501898e+06
Charlotte Hornets       17.133333  26.133333  220.400000  5.222728e+06
Chicago Bulls           19.200000  27.400000  218.933333  5.785559e+06
Cleveland Cavaliers     14.466667  29.533333  227.866667  7.642049e+06
Dallas Mavericks        20.000000  29.733333  227.000000  4.746582e+06
Denver Nuggets          15.266667  25.733333  217.533333  4.294424e+06
Detroit Pistons         17.266667  26.200000  222.200000  4.477884e+06
Golden State Warriors   20.866667  27.666667  224.600000  5.924600e+06
Houston Rockets         14.666667  26.866667  220.333333  5.018868e+06
Indiana Pacers          18.933333  26.400000  222.266667  4.450122e+06
Los Angeles Clippers    19.533333  29.466667  219.733333  6.323643e+06
Los Angeles Lakers      16.066667  27.533333  227.066667  4.784695e+06
Memphis Grizzlies       15.555556  28.388889  218.000000  5.467920e+06
Miami Heat              10.466667  28.933333  218.400000  6.347359e+06
Milwaukee Bucks         20.000000  24.562500  224.062500  4.350220e+06
Minnesota Timberwolves  19.571429  26.357143  228.642857  4.593054e+06
New Orleans Pelicans    17.000000  26.894737  221.000000  4.355304e+06
New York Knicks         13.250000  27.000000  223.625000  4.581494e+06
Oklahoma City Thunder   14.000000  27.066667  229.400000  6.251020e+06
Orlando Magic           16.428571  25.071429  213.357143  4.297248e+06
Philadelphia 76ers      18.066667  24.600000  222.133333  2.213778e+06
Phoenix Suns            15.466667  25.866667  218.600000  4.229676e+06
Portland Trail Blazers  16.000000  25.066667  218.600000  3.220121e+06
Sacramento Kings        16.933333  26.800000  221.333333  4.778911e+06
San Antonio Spurs       17.933333  31.600000  223.933333  5.629516e+06
Toronto Raptors         22.466667  26.133333  221.800000  4.741174e+06
Utah Jazz               17.866667  24.466667  220.000000  4.204006e+06
Washington Wizards      17.600000  27.866667  219.000000  5.088576e+06

In [7]:
df.groupby(['Team']).mean().sort_values('Salary',ascending=False)

                           Number        Age      Weight        Salary
Team
Cleveland Cavaliers     14.466667  29.533333  227.866667  7.642049e+06
Miami Heat              10.466667  28.933333  218.400000  6.347359e+06
Los Angeles Clippers    19.533333  29.466667  219.733333  6.323643e+06
Oklahoma City Thunder   14.000000  27.066667  229.400000  6.251020e+06
Golden State Warriors   20.866667  27.666667  224.600000  5.924600e+06
Chicago Bulls           19.200000  27.400000  218.933333  5.785559e+06
San Antonio Spurs       17.933333  31.600000  223.933333  5.629516e+06
Memphis Grizzlies       15.555556  28.388889  218.000000  5.467920e+06
Charlotte Hornets       17.133333  26.133333  220.400000  5.222728e+06
Washington Wizards      17.600000  27.866667  219.000000  5.088576e+06
Houston Rockets         14.666667  26.866667  220.333333  5.018868e+06
Atlanta Hawks           19.000000  28.200000  221.266667  4.860197e+06
Los Angeles Lakers      16.066667  27.533333  227.066667  4.784695e+06
Sacramento Kings        16.933333  26.800000  221.333333  4.778911e+06
Dallas Mavericks        20.000000  29.733333  227.000000  4.746582e+06
Toronto Raptors         22.466667  26.133333  221.800000  4.741174e+06
Minnesota Timberwolves  19.571429  26.357143  228.642857  4.593054e+06
New York Knicks         13.250000  27.000000  223.625000  4.581494e+06
Detroit Pistons         17.266667  26.200000  222.200000  4.477884e+06
Indiana Pacers          18.933333  26.400000  222.266667  4.450122e+06
New Orleans Pelicans    17.000000  26.894737  221.000000  4.355304e+06
Milwaukee Bucks         20.000000  24.562500  224.062500  4.350220e+06
Orlando Magic           16.428571  25.071429  213.357143  4.297248e+06
Denver Nuggets          15.266667  25.733333  217.533333  4.294424e+06
Phoenix Suns            15.466667  25.866667  218.600000  4.229676e+06
Utah Jazz               17.866667  24.466667  220.000000  4.204006e+06
Boston Celtics          31.866667  24.733333  219.466667  4.181505e+06
Brooklyn Nets           18.266667  25.600000  215.600000  3.501898e+06
Portland Trail Blazers  16.000000  25.066667  218.600000  3.220121e+06
Philadelphia 76ers      18.066667  24.600000  222.133333  2.213778e+06

In [8]:
df.groupby(['Team']).sum()

                        Number    Age  Weight       Salary
Team
Atlanta Hawks            285.0  423.0  3319.0   72902950.0
Boston Celtics           478.0  371.0  3292.0   58541068.0
Brooklyn Nets            274.0  384.0  3234.0   52528475.0
Charlotte Hornets        257.0  392.0  3306.0   78340920.0
Chicago Bulls            288.0  411.0  3284.0   86783378.0
Cleveland Cavaliers      217.0  443.0  3418.0  106988689.0
Dallas Mavericks         300.0  446.0  3405.0   71198732.0
Denver Nuggets           229.0  386.0  3263.0   60121930.0
Detroit Pistons          259.0  393.0  3333.0   67168263.0
Golden State Warriors    313.0  415.0  3369.0   88868997.0
Houston Rockets          220.0  403.0  3305.0   75283021.0
Indiana Pacers           284.0  396.0  3334.0   66751826.0
Los Angeles Clippers     293.0  442.0  3296.0   94854640.0
Los Angeles Lakers       241.0  413.0  3406.0   71770431.0
Memphis Grizzlies        280.0  511.0  3924.0   76550880.0
Miami Heat               157.0  434.0  3276.0   82515673.0
Milwaukee Bucks          320.0  393.0  3585.0   69603517.0
Minnesota Timberwolves   274.0  369.0  3201.0   59709697.0
New Orleans Pelicans     323.0  511.0  4199.0   82750774.0
New York Knicks          212.0  432.0  3578.0   73303898.0
Oklahoma City Thunder    210.0  406.0  3441.0   93765298.0
Orlando Magic            230.0  351.0  2987.0   60161470.0
Philadelphia 76ers       271.0  369.0  3332.0   30992894.0
Phoenix Suns             232.0  388.0  3279.0   63445135.0
Portland Trail Blazers   240.0  376.0  3279.0   48301818.0
Sacramento Kings         254.0  402.0  3320.0   71683666.0
San Antonio Spurs        269.0  474.0  3359.0   84442733.0
Toronto Raptors          337.0  392.0  3327.0   71117611.0
Utah Jazz                268.0  367.0  3300.0   63060091.0
Washington Wizards       264.0  418.0  3285.0   76328636.0

In [9]:
gk=df.groupby('Team')
gk.first()

,Name,Number,Position,Age,Height,Weight,College,Salary
Team,,,,,,,,
Atlanta Hawks,Kent Bazemore,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
Boston Celtics,Avery Bradley,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Brooklyn Nets,Bojan Bogdanovic,44.0,SG,27.0,6-8,216.0,Oklahoma State,3425510.0
Charlotte Hornets,Nicolas Batum,5.0,SG,27.0,6-8,200.0,Virginia Commonwealth,13125306.0
Chicago Bulls,Cameron Bairstow,41.0,PF,25.0,6-9,250.0,New Mexico,845059.0
Cleveland Cavaliers,Matthew Dellavedova,8.0,PG,25.0,6-4,198.0,Saint Mary's,1147276.0
Dallas Mavericks,Justin Anderson,1.0,SG,22.0,6-6,228.0,Virginia,1449000.0
Denver Nuggets,Darrell Arthur,0.0,PF,28.0,6-9,235.0,Kansas,2814000.0
Detroit Pistons,Joel Anthony,50.0,C,33.0,6-9,245.0,UNLV,2500000.0
Golden State Warriors,Leandro Barbosa,19.0,SG,33.0,6-3,194.0,North Carolina,2500000.0
Houston Rockets,Trevor Ariza,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
Indiana Pacers,Lavoy Allen,5.0,PF,27.0,6-9,255.0,Temple,4050000.0
Los Angeles Clippers,Cole Aldrich,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
Los Angeles Lakers,Brandon Bass,2.0,PF,31.0,6-8,250.0,LSU,3000000.0
Memphis Grizzlies,Jordan Adams,3.0,SG,21.0,6-5,209.0,UCLA,1404600.0
Miami Heat,Chris Bosh,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
Milwaukee Bucks,Giannis Antetokounmpo,34.0,SF,21.0,6-11,222.0,Arizona,1953960.0
Minnesota Timberwolves,Nemanja Bjelica,88.0,PF,28.0,6-10,240.0,Louisville,3950001.0
New Orleans Pelicans,Alexis Ajinca,42.0,C,28.0,7-2,248.0,California,4389607.0
New York Knicks,Arron Afflalo,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
Oklahoma City Thunder,Steven Adams,12.0,C,22.0,7-0,255.0,Pittsburgh,2279040.0
Orlando Magic,Dewayne Dedmon,3.0,C,26.0,7-0,245.0,USC,947276.0
Philadelphia 76ers,Elton Brand,42.0,PF,37.0,6-9,254.0,Duke,947276.0
Phoenix Suns,Eric Bledsoe,2.0,PG,26.0,6-1,190.0,Kentucky,13500000.0
Portland Trail Blazers,Cliff Alexander,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
Sacramento Kings,Quincy Acy,13.0,SF,25.0,6-7,240.0,Baylor,981348.0
San Antonio Spurs,LaMarcus Aldridge,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
Toronto Raptors,Bismack Biyombo,8.0,C,23.0,6-9,245.0,Missouri,2814000.0
Utah Jazz,Trevor Booker,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
Washington Wizards,Alan Anderson,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0

In [10]:
gk.get_group('Oklahoma City Thunder')

,Age,College,Height,Name,Number,Position,Salary,Weight
412,22.0,Pittsburgh,7-0,Steven Adams,12.0,C,2279040.0,255.0
413,35.0,Kansas,6-10,Nick Collison,4.0,PF,3750000.0,255.0
414,27.0,Texas,6-9,Kevin Durant,35.0,SF,20158622.0,240.0
415,32.0,Villanova,6-4,Randy Foye,6.0,SG,3135000.0,213.0
416,24.0,Stanford,6-7,Josh Huestis,34.0,SF,1140240.0,230.0
417,26.0,NaN,6-10,Serge Ibaka,9.0,PF,12250000.0,245.0
418,24.0,Kentucky,6-11,Enes Kanter,11.0,C,16407500.0,245.0
419,24.0,Michigan,6-10,Mitch McGary,33.0,PF,1463040.0,255.0
420,38.0,Kentucky,6-10,Nazr Mohammed,13.0,C,222888.0,250.0
421,30.0,Georgia Tech,6-5,Anthony Morrow,2.0,SG,3344000.0,210.0
422,21.0,Murray State,6-3,Cameron Payne,22.0,PG,2021520.0,185.0
423,24.0,Colorado,6-7,Andre Roberson,21.0,SG,1210800.0,210.0
424,28.0,Duke,6-8,Kyle Singler,5.0,SF,4500000.0,228.0
425,24.0,Syracuse,6-4,Dion Waiters,3.0,SG,5138430.0,220.0
426,27.0,UCLA,6-3,Russell Westbrook,0.0,PG,16744218.0,200.0